[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tagstr_site"
version = "0.0.1"
description = "Collection of tag string demos, docs, and contributions."
requires-python = ">=3.12"
dependencies = [
    "pytest~=7.4.3",
    "sphinx",
    "sphinx-book-theme",
    "pytest-sphinx",
    "sphinx-autobuild",
    "sybil",
    "myst-parser"
]


[project.optional-dependencies]
jupyterlite = ["jupyterlite-core[all]~=0.2.0", "jupyterlite-pyodide-kernel~=0.2.0", "ipython~=8.17.2"]

[tool.pytest.ini_options]
addopts = "-ra -q --doctest-modules --ignore-glob='**/_build/**'"
testpaths = ["tests", "docs"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20